// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package via.sep3.databaseserver.protobuff;

public interface BoolMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BoolMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>int32 driverId = 2;</code>
   * @return The driverId.
   */
  int getDriverId();
}
