// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

public interface IdMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IdMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 driverId = 1;</code>
   * @return The driverId.
   */
  int getDriverId();
}
