// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

public interface JoinRideMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JoinRideMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rideId = 1;</code>
   * @return The rideId.
   */
  int getRideId();

  /**
   * <code>string passengerName = 2;</code>
   * @return The passengerName.
   */
  java.lang.String getPassengerName();
  /**
   * <code>string passengerName = 2;</code>
   * @return The bytes for passengerName.
   */
  com.google.protobuf.ByteString
      getPassengerNameBytes();

  /**
   * <code>string passengerPhone = 3;</code>
   * @return The passengerPhone.
   */
  java.lang.String getPassengerPhone();
  /**
   * <code>string passengerPhone = 3;</code>
   * @return The bytes for passengerPhone.
   */
  com.google.protobuf.ByteString
      getPassengerPhoneBytes();
}
