// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

/**
 * Protobuf type {@code JoinRideMessage}
 */
public final class JoinRideMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:JoinRideMessage)
    JoinRideMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use JoinRideMessage.newBuilder() to construct.
  private JoinRideMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private JoinRideMessage() {
    passengerName_ = "";
    passengerPhone_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new JoinRideMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private JoinRideMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            rideId_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            passengerName_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            passengerPhone_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_JoinRideMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_JoinRideMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sep3.databaseserver.protobuff.JoinRideMessage.class, via.sep3.databaseserver.protobuff.JoinRideMessage.Builder.class);
  }

  public static final int RIDEID_FIELD_NUMBER = 1;
  private int rideId_;
  /**
   * <code>int32 rideId = 1;</code>
   * @return The rideId.
   */
  @java.lang.Override
  public int getRideId() {
    return rideId_;
  }

  public static final int PASSENGERNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object passengerName_;
  /**
   * <code>string passengerName = 2;</code>
   * @return The passengerName.
   */
  @java.lang.Override
  public java.lang.String getPassengerName() {
    java.lang.Object ref = passengerName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      passengerName_ = s;
      return s;
    }
  }
  /**
   * <code>string passengerName = 2;</code>
   * @return The bytes for passengerName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPassengerNameBytes() {
    java.lang.Object ref = passengerName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      passengerName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSENGERPHONE_FIELD_NUMBER = 3;
  private volatile java.lang.Object passengerPhone_;
  /**
   * <code>string passengerPhone = 3;</code>
   * @return The passengerPhone.
   */
  @java.lang.Override
  public java.lang.String getPassengerPhone() {
    java.lang.Object ref = passengerPhone_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      passengerPhone_ = s;
      return s;
    }
  }
  /**
   * <code>string passengerPhone = 3;</code>
   * @return The bytes for passengerPhone.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPassengerPhoneBytes() {
    java.lang.Object ref = passengerPhone_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      passengerPhone_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (rideId_ != 0) {
      output.writeInt32(1, rideId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(passengerName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, passengerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(passengerPhone_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, passengerPhone_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (rideId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, rideId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(passengerName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, passengerName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(passengerPhone_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, passengerPhone_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sep3.databaseserver.protobuff.JoinRideMessage)) {
      return super.equals(obj);
    }
    via.sep3.databaseserver.protobuff.JoinRideMessage other = (via.sep3.databaseserver.protobuff.JoinRideMessage) obj;

    if (getRideId()
        != other.getRideId()) return false;
    if (!getPassengerName()
        .equals(other.getPassengerName())) return false;
    if (!getPassengerPhone()
        .equals(other.getPassengerPhone())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RIDEID_FIELD_NUMBER;
    hash = (53 * hash) + getRideId();
    hash = (37 * hash) + PASSENGERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getPassengerName().hashCode();
    hash = (37 * hash) + PASSENGERPHONE_FIELD_NUMBER;
    hash = (53 * hash) + getPassengerPhone().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sep3.databaseserver.protobuff.JoinRideMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sep3.databaseserver.protobuff.JoinRideMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code JoinRideMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:JoinRideMessage)
      via.sep3.databaseserver.protobuff.JoinRideMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_JoinRideMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_JoinRideMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sep3.databaseserver.protobuff.JoinRideMessage.class, via.sep3.databaseserver.protobuff.JoinRideMessage.Builder.class);
    }

    // Construct using via.sep3.databaseserver.protobuff.JoinRideMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      rideId_ = 0;

      passengerName_ = "";

      passengerPhone_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sep3.databaseserver.protobuff.RidesOuterClass.internal_static_JoinRideMessage_descriptor;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.JoinRideMessage getDefaultInstanceForType() {
      return via.sep3.databaseserver.protobuff.JoinRideMessage.getDefaultInstance();
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.JoinRideMessage build() {
      via.sep3.databaseserver.protobuff.JoinRideMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sep3.databaseserver.protobuff.JoinRideMessage buildPartial() {
      via.sep3.databaseserver.protobuff.JoinRideMessage result = new via.sep3.databaseserver.protobuff.JoinRideMessage(this);
      result.rideId_ = rideId_;
      result.passengerName_ = passengerName_;
      result.passengerPhone_ = passengerPhone_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sep3.databaseserver.protobuff.JoinRideMessage) {
        return mergeFrom((via.sep3.databaseserver.protobuff.JoinRideMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sep3.databaseserver.protobuff.JoinRideMessage other) {
      if (other == via.sep3.databaseserver.protobuff.JoinRideMessage.getDefaultInstance()) return this;
      if (other.getRideId() != 0) {
        setRideId(other.getRideId());
      }
      if (!other.getPassengerName().isEmpty()) {
        passengerName_ = other.passengerName_;
        onChanged();
      }
      if (!other.getPassengerPhone().isEmpty()) {
        passengerPhone_ = other.passengerPhone_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sep3.databaseserver.protobuff.JoinRideMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sep3.databaseserver.protobuff.JoinRideMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int rideId_ ;
    /**
     * <code>int32 rideId = 1;</code>
     * @return The rideId.
     */
    @java.lang.Override
    public int getRideId() {
      return rideId_;
    }
    /**
     * <code>int32 rideId = 1;</code>
     * @param value The rideId to set.
     * @return This builder for chaining.
     */
    public Builder setRideId(int value) {
      
      rideId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rideId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRideId() {
      
      rideId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object passengerName_ = "";
    /**
     * <code>string passengerName = 2;</code>
     * @return The passengerName.
     */
    public java.lang.String getPassengerName() {
      java.lang.Object ref = passengerName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passengerName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string passengerName = 2;</code>
     * @return The bytes for passengerName.
     */
    public com.google.protobuf.ByteString
        getPassengerNameBytes() {
      java.lang.Object ref = passengerName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passengerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string passengerName = 2;</code>
     * @param value The passengerName to set.
     * @return This builder for chaining.
     */
    public Builder setPassengerName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passengerName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string passengerName = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassengerName() {
      
      passengerName_ = getDefaultInstance().getPassengerName();
      onChanged();
      return this;
    }
    /**
     * <code>string passengerName = 2;</code>
     * @param value The bytes for passengerName to set.
     * @return This builder for chaining.
     */
    public Builder setPassengerNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      passengerName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object passengerPhone_ = "";
    /**
     * <code>string passengerPhone = 3;</code>
     * @return The passengerPhone.
     */
    public java.lang.String getPassengerPhone() {
      java.lang.Object ref = passengerPhone_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        passengerPhone_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string passengerPhone = 3;</code>
     * @return The bytes for passengerPhone.
     */
    public com.google.protobuf.ByteString
        getPassengerPhoneBytes() {
      java.lang.Object ref = passengerPhone_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        passengerPhone_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string passengerPhone = 3;</code>
     * @param value The passengerPhone to set.
     * @return This builder for chaining.
     */
    public Builder setPassengerPhone(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passengerPhone_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string passengerPhone = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassengerPhone() {
      
      passengerPhone_ = getDefaultInstance().getPassengerPhone();
      onChanged();
      return this;
    }
    /**
     * <code>string passengerPhone = 3;</code>
     * @param value The bytes for passengerPhone to set.
     * @return This builder for chaining.
     */
    public Builder setPassengerPhoneBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      passengerPhone_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:JoinRideMessage)
  }

  // @@protoc_insertion_point(class_scope:JoinRideMessage)
  private static final via.sep3.databaseserver.protobuff.JoinRideMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sep3.databaseserver.protobuff.JoinRideMessage();
  }

  public static via.sep3.databaseserver.protobuff.JoinRideMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<JoinRideMessage>
      PARSER = new com.google.protobuf.AbstractParser<JoinRideMessage>() {
    @java.lang.Override
    public JoinRideMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new JoinRideMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<JoinRideMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<JoinRideMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sep3.databaseserver.protobuff.JoinRideMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

