// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

public interface JoinRideMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:JoinRideMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 rideId = 1;</code>
   * @return The rideId.
   */
  int getRideId();

  /**
   * <code>int32 passengerId = 2;</code>
   * @return The passengerId.
   */
  int getPassengerId();
}
