// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

public interface NullMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NullMessage)
    com.google.protobuf.MessageOrBuilder {
}
