// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reservation.proto

package via.sep3.databaseserver.protobuff;

public final class Reservation {
  private Reservation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AcceptMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AcceptMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BoolValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BoolValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NullMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NullMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationsToAcceptCollection_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationsToAcceptCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Reservation.proto\"9\n\rAcceptMessage\022\025\n\r" +
      "reservationId\030\001 \001(\005\022\021\n\tdidAccept\030\002 \001(\010\"\032" +
      "\n\tBoolValue\022\r\n\005value\030\001 \001(\010\"\177\n\022Reservatio" +
      "nMessage\022\016\n\006rideId\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\r" +
      "\n\005phone\030\003 \001(\t\022\"\n\tdidAccept\030\004 \001(\0132\n.BoolV" +
      "alueH\000\210\001\001\022\n\n\002id\030\005 \001(\005B\014\n\n_didAccept\"\r\n\013N" +
      "ullMessage\"R\n\036ReservationsToAcceptCollec" +
      "tion\0220\n\023reservationMessages\030\001 \003(\0132\023.Rese" +
      "rvationMessage2\223\001\n\014Reservations\0226\n\017accep" +
      "tPassenger\022\016.AcceptMessage\032\023.Reservation" +
      "Message\022K\n\032getAllReservationsToAccept\022\014." +
      "NullMessage\032\037.ReservationsToAcceptCollec" +
      "tionB%\n!via.sep3.databaseserver.protobuf" +
      "fP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AcceptMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AcceptMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AcceptMessage_descriptor,
        new java.lang.String[] { "ReservationId", "DidAccept", });
    internal_static_BoolValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BoolValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BoolValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_ReservationMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReservationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationMessage_descriptor,
        new java.lang.String[] { "RideId", "Name", "Phone", "DidAccept", "Id", "DidAccept", });
    internal_static_NullMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_NullMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NullMessage_descriptor,
        new java.lang.String[] { });
    internal_static_ReservationsToAcceptCollection_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ReservationsToAcceptCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationsToAcceptCollection_descriptor,
        new java.lang.String[] { "ReservationMessages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
