// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

public interface RidesCollectionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RidesCollection)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .RidesCollection.RideMessage rides = 1;</code>
   */
  java.util.List<via.sep3.databaseserver.protobuff.RidesCollection.RideMessage> 
      getRidesList();
  /**
   * <code>repeated .RidesCollection.RideMessage rides = 1;</code>
   */
  via.sep3.databaseserver.protobuff.RidesCollection.RideMessage getRides(int index);
  /**
   * <code>repeated .RidesCollection.RideMessage rides = 1;</code>
   */
  int getRidesCount();
  /**
   * <code>repeated .RidesCollection.RideMessage rides = 1;</code>
   */
  java.util.List<? extends via.sep3.databaseserver.protobuff.RidesCollection.RideMessageOrBuilder> 
      getRidesOrBuilderList();
  /**
   * <code>repeated .RidesCollection.RideMessage rides = 1;</code>
   */
  via.sep3.databaseserver.protobuff.RidesCollection.RideMessageOrBuilder getRidesOrBuilder(
      int index);
}
