// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Rides.proto

package via.sep3.databaseserver.protobuff;

public interface RideMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RideMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.LocationMessage startLocation = 2;</code>
   * @return Whether the startLocation field is set.
   */
  boolean hasStartLocation();
  /**
   * <code>.LocationMessage startLocation = 2;</code>
   * @return The startLocation.
   */
  via.sep3.databaseserver.protobuff.LocationMessage getStartLocation();
  /**
   * <code>.LocationMessage startLocation = 2;</code>
   */
  via.sep3.databaseserver.protobuff.LocationMessageOrBuilder getStartLocationOrBuilder();

  /**
   * <code>.LocationMessage destination = 3;</code>
   * @return Whether the destination field is set.
   */
  boolean hasDestination();
  /**
   * <code>.LocationMessage destination = 3;</code>
   * @return The destination.
   */
  via.sep3.databaseserver.protobuff.LocationMessage getDestination();
  /**
   * <code>.LocationMessage destination = 3;</code>
   */
  via.sep3.databaseserver.protobuff.LocationMessageOrBuilder getDestinationOrBuilder();

  /**
   * <code>int64 startDate = 4;</code>
   * @return The startDate.
   */
  long getStartDate();

  /**
   * <code>string driver = 5;</code>
   * @return The driver.
   */
  java.lang.String getDriver();
  /**
   * <code>string driver = 5;</code>
   * @return The bytes for driver.
   */
  com.google.protobuf.ByteString
      getDriverBytes();

  /**
   * <code>int32 capacity = 6;</code>
   * @return The capacity.
   */
  int getCapacity();
}
